// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://mas22m6xj5f77avjtb7hx2it4e.appsync-api.eu-north-1.amazonaws.com/graphql',
          region: 'eu-north-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-ux3y3w4pejfgdf3prhj6sxnzgi'
        }
    }
};

export default config;